---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  sudo: True
  roles:
    - common
    - web
    - mariadb
    - varnish
    - redis
  vars:
    wtf: hello_yes