---
# This playbook contains common plays that will be run on all nodes.

- name: install packages
  apt: name={{ item }} state=present
  with_items:
     - php5-xdebug
     - php5-xhprof
     - graphviz
     - php-pear

- name: copy php debug configurations
  template: src={{ conf }}.php.j2  dest=/etc/php5/{{ item.type }}/conf.d/{{ item.conf }}.ini mode=0755
  with_items:
    - {conf: xdebug, type: cli }
    - {conf: xdebug, type: fpm }
    - {conf: xhprof, type: cli }
    - {conf: xhprof, type: fpm }