---
# Handler for the webtier: handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: reload varnish
  service: name=varnish state=reloaded

- name: restart varnish
  service: name=varnish state=restarted