---
# This playbook contains common plays that will be run on all nodes.

- name: install packages
  apt: name={{ item }} state=present
  with_items:
     - nginx
     - php5
     - php5-fpm
     - php5-cli

- name: create web dir
  file: path=/var/www state=directory mode="0777"

- name: copy index.php
  template: src=index.php.j2 dest=/var/www/index.php mode=0755

- template: src=composer.json dest=/var/www/composer.json mode=0755

- name: nginx sites enabled
  notify: "restart nginx"
  template: src=nginx-site-default.conf.j2 dest=/etc/nginx/sites-enabled/default

- name: php.ini for php
  template: src=php.ini-{{ item }}.j2 dest=/etc/php5/{{ item }}/php.ini
  notify: "restart fpm"
  with_items:
    - cli
    - fpm
